<script setup lang="ts">
useHead({
  title: "Create Turborepo (vue-nuxt:docs)",
  meta: [{ name: "description", content: "Generated by create turbo" }],
});
</script>

<template>
  <NuxtPage />
</template>
